Check this out! I'm trying fr to get a raw f string! I think it might have worked!
So now... there's something happening in mogrify? query = query % self._escape_args(args, conn)
TypeError: not all arguments converted during string formatting
???

I assume there's something wrong with crsr.execute(sql, 'root'), because I used to have (user) where I now have 'root', but then it was complaining about not knowing what (user) was, because that had been defined in my reference to the .env, and for some reason that whole thing wasn't working. Actually, I think I might have an easy solution for this... one sec...

No, look, that didn't work! I even put ALL the variables in the argument of loadpic! Still no dice!

I was wondering if I forgot to use quotation marks... well, that didn't seem to change anything!

I feel like I should get better at debugging. Not that that would necessarily help? Where I am just confused by a weird error? I'll look at it tomorrow!