Oh right, I totally spaced and left that 'const obj = obj[rand].parse()' there! Sooo... in order to extract multiple elements from a json... well, first I need to make sure it's parsing right, or whatever.
So, what inspect says, is 'VM97:1
 Uncaught (in promise)
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON'. I can't find my invalid JSON!!!